AWSTemplateFormatVersion: "2010-09-09"
Description: Frontend rendering service

Parameters:
    App:
        Description: Application name
        Type: String
        Default: moonmicro
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - CODE
        Default: CODE
    Stack:
        Description: Stack name
        Type: String
        Default: frontend

Resources:
    Role:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                             - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /
            Policies:
                - PolicyName: logs
                  PolicyDocument:
                      Statement:
                          Effect: Allow
                          Action:
                              - logs:CreateLogGroup
                              - logs:CreateLogStream
                              - logs:PutLogEvents
                          Resource: arn:aws:logs:*:*:*
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                            - lambda:InvokeFunction
                            Resource: "*"
