---
AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Creates an ECR (Elastic Container Registry) for storing Docker images

Parameters:
  RepositoryName:
    Type: String

Resources:

  Repository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref RepositoryName
      # TODO add some kind of lifecycle policy
